tbcompanion/posts/forms.py
from flask_login import current_user
from flask_pagedown.fields import PageDownField
from flask_wtf.form import FlaskForm
from wtforms.fields.core import IntegerField, StringField
from wtforms.fields.simple import SubmitField
from wtforms.validators import DataRequired, Length, ValidationError

from tbcompanion.models import Project


class PostForm(FlaskForm):
	"""This is the form used to create new posts."""

	title = StringField('Title', validators=[
		DataRequired(),
		Length(max=120)
	])
	content = PageDownField('Insert Text Here', validators=[
		DataRequired()
	])
	project_id = IntegerField('This post is related to project-ID:', validators=[
		DataRequired(),
	])
	submit = SubmitField('Publish post')

	def validate_project_id(self, project_id):
		"""Check that 'project_id.data' corresponds to the ID of any existing project in the database."""

		project = Project.query.filter_by(id=project_id.data).first()

		"""Raise ValidationError if the project exists but the current user is not a contributor,
		   or if the project does not exist."""
		if project and current_user not in project.contributors:
			raise ValidationError('You are not contributing to this project. '
								  'Please leave a comment on the project\'s page instead.')
		elif not project:
			raise ValidationError('This project does not exist.')

tbcompanion/accounts/routes.py
from flask import Blueprint, render_template, request, url_for
from flask.helpers import flash
from flask_login import current_user
from flask_login.utils import login_required
from flask_mail import Message
from tbcompanion import bcrypt, db, mail
from tbcompanion.accounts.forms import (ForgotPassword, PasswordReset,
										RegistrationForm, UpdateAccount)
from tbcompanion.models import Post, User
from werkzeug.utils import redirect

accounts = Blueprint('accounts', __name__)


@accounts.route('/register', methods=['GET', 'POST'])
def register():
	"""This is the page where new users can register."""

	if current_user.is_authenticated:  # User must not be logged in. Redirect to registration page if False.
		flash('You are already registered!')
		return redirect(url_for('main.home'))

	form = RegistrationForm()

	if form.validate_on_submit():
		hashed_pass = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(username=form.username.data,
					email=form.email.data,
					password=hashed_pass)

		db.session.add(user)
		db.session.commit()

		flash(f'Welcome, {form.username.data}!', 'success')
		return redirect(url_for('main.home'))

	return render_template('register.html', title='Register', form=form)

# TODO: E-mail confirmation


@accounts.route('/account', methods=['GET', 'POST'])
@login_required
def account_page():
	"""This is the page where registered, logged-in users can see their own profile and update their account info."""

	posts = Post.query.filter_by(author=current_user).all()
	projects = current_user.contribution_id

	form = UpdateAccount()

	if form.validate_on_submit():
		current_user.username = form.username.data
		current_user.email = form.email.data

		db.session.commit()  # User already exists, just need to commit new data.

		flash('You have updated your account.', 'success')
		return redirect(url_for('accounts.account_page'))

	elif request.method == 'GET':  # Fills form fields with the user's information.
		form.username.data = current_user.username
		form.email.data = current_user.email

	return render_template('account.html',
						   title=current_user.username,
						   user=current_user,
						   form=form,
						   posts=posts,
						   projects=projects)


# TODO: Expand UpdateAccount.

def send_password_reset_email(user):
	"""Uses flask_mail to sends users an email with a link to reset their password."""

	token = user.get_reset_token()  # Carries over to .password_reset
	msg = Message(  # flask_mail.Message
		'TBCOMP::password_reset',
		sender='serban.gorga@gmail.com',
		recipients=[user.email])
	msg.body = ("If you requested a password reset, click this link to reset your password:\n"
				f"{url_for('accounts.password_reset', token=token, _external=True)}\n"  # Redirects to .password_reset
				"TBCOMP@DEV_GiorginoSerbuciano")
	mail.send(msg)  # flask_mail._MailMixin.send


@accounts.route('/passwordReset', methods=['GET', 'POST'])
def password_reset_request():
	"""Allows users to request an email with a password reset link to be sent to their email address."""

	if current_user.is_authenticated:  # User must not be logged in.
		return redirect(url_for('main.home'))

	form = ForgotPassword()  # Asks for user email.

	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		send_password_reset_email(user)

		flash('If this email corresponds to a registered account,'
			  'you will shortly receive an email with a link to reset your password.',
			  'info')  # This vague formulation does not reveal whether an account exists under the given email.
		return redirect(url_for('users.login'))

	return render_template('password_reset_request.html',
						   title='Reset Password',
						   form=form)


@accounts.route('/passwordReset/<token>', methods=['GET','POST'])
def password_reset(token):
	"""Password reset link redirects to this page. Resets user's password. """

	if current_user.is_authenticated:  # User must not be logged in.
		return redirect(url_for('main.home'))

	user = User.validate_reset_token(token)  # See .send_password_reset_email

	if not user:  # Checks if the current token is (still) valid.
		flash('Invalid token!', 'warning')
		return redirect(url_for('accounts.password_reset_request'))

	form = PasswordReset()

	if form.validate_on_submit():
		hashed_pass = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user.password = hashed_pass
		# db.session.commit()?

		flash('You\'ve set a new password!', 'success')
		return redirect(url_for('users.login'))

	return render_template('password_reset.html',
						   title='Set a new password',
						   form=form)

tbcompanion/admin/routes.py
from flask import Blueprint, render_template, redirect, url_for

admin = Blueprint('admin', __name__)


@admin.route('/admin', methods=['GET', 'POST'])
def admin_panel():
	"""Placeholder for future implementation"""

	return redirect(url_for('main.home'))

tbcompanion/main/routes.py
import os

from flask import Blueprint, render_template, request, redirect, url_for, session, jsonify
from requests_oauthlib import OAuth2Session
from sqlalchemy import desc

from tbcompanion.main.forms import SearchBox
from tbcompanion.models import Post, Project, User

main = Blueprint('main', __name__)

os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'  # Allows HTTP for testing.
client_id = os.environ.get('TBCOMP_CLIENT_ID')
client_secret = os.environ.get('TBCOMP_CLIENT_SECRET')
authorization_base_url = 'https://github.com/login/oauth/authorize'
token_url = 'https://github.com/login/oauth/access_token'


@main.route('/github_authorization')
def github_authorization():
	"""Access the Github app authorization page."""

	g = OAuth2Session(client_id)
	authorization_url, state = g.authorization_url(authorization_base_url)
	session['oauth_state'] = state  # Attack protection
	return redirect(authorization_url)


@main.route('/callback')
def callback():
	"""Callback from Github authorization."""

	g = OAuth2Session(client_id, state=session['oauth_state'])
	token = g.fetch_token(token_url,
						  client_secret=client_secret,
						  authorization_response=request.url)
	session['oauth_token'] = token
	return redirect(url_for('.home'))


@main.route('/github_profile/user', methods=['GET'])
def github_user_profile():
	"""An example of how to access a protected resource using an authorized session."""

	g = OAuth2Session(client_id, token=session['oauth_token'])  # token must be used for every definition of 'g'
	return jsonify(g.get('https://api.github.com/user').json())


@main.route('/', methods=['GET', 'POST'])
def home():
	"""Home page."""

	posts = Post.query.order_by(desc('date')).all()
	projects = Project.query.order_by(desc('date')).all()

	form = SearchBox()

	"""Placeholder for a future implementation."""
	if form.validate_on_submit():
		return redirect(url_for('main.search_result', string=form.string.data))

	return render_template('home.html',
						   title='Home',
						   form=form,
						   posts=posts,
						   projects=projects,
						   )


@main.route('/about')
def about():
	"""The 'about' page."""
	return render_template('about.html', title='About')

	# TODO: Update privacy information.


@main.route('/search')
def search_result():
	"""Placeholder for a future implementation."""

	string = request.args.get('string')
	posts = Post.query.filter_by(title=string).all()
	projects = Project.query.filter_by(title=string).all()
	users = User.query.filter_by(username=string).all()

	return render_template('search_result.html',
						   users=users,
						   posts=posts,
						   projects=projects,
						   string=string
						   )

tbcompanion/posts/routes.py
from flask import Blueprint, render_template, request, url_for
from flask.helpers import flash
from flask_login import current_user
from flask_login.utils import login_required
from werkzeug.exceptions import abort
from werkzeug.utils import redirect

from tbcompanion import db
from tbcompanion.models import Post
from tbcompanion.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route('/post/<int:post_id>', methods=['GET'])
def post(post_id):
	"""This page displays a post."""
	post_query = Post.query.get_or_404(post_id)
	return render_template('post_view.html', post=post_query)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def post_form():
	"""This is the page for creating a new post."""

	form = PostForm()

	if form.validate_on_submit():
		new_post = Post(
			title=form.title.data, 
			content=form.content.data, 
			author=current_user,
			project_id=form.project_id.data)

		db.session.add(new_post)
		db.session.commit()

		flash('You have published your post!', 'success')
		return redirect(url_for('main.home'))

	return render_template('post_form.html', form=form, title='New Post')


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
	"""This is the page for updating an already-existing post."""

	post_query = Post.query.get_or_404(post_id)

	if post_query.author != current_user:  # Only the post's author can edit it.
		abort(403)

	form = PostForm()

	if form.validate_on_submit():
		post_query.title = form.title.data
		post_query.content = form.content.data

		db.session.commit()

		flash('You have updated your post!', 'success')
		return redirect(url_for('posts.post', post_id=post_query.id))

	elif request.method == 'GET':  # Fill in form fields with the posts' content.
		form.title.data = post.title
		form.content.data = post.content

	return render_template('post_form.html', form=form, title='New Post')


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
def delete_post(post_id):
	"""This is the route that deletes posts."""

	post_query = Post.query.get_or_404(post_id)

	if post_query.author != current_user:  # Only the post's author can delete it.
		print(current_user)
		abort(403)

	db.session.delete(post_query)
	db.session.commit()

	flash('You have deleted your post!', 'danger')
	return redirect(url_for('main.home'))

tbcompanion/projects/routes.py
import base64

from flask import Blueprint, render_template, url_for
from flask.helpers import flash
from flask_login import current_user
from flask_login.utils import login_required
from requests_oauthlib import OAuth2Session
from werkzeug.utils import redirect

from tbcompanion import db
from tbcompanion.main.routes import client_id, session
from tbcompanion.models import Project, User
from tbcompanion.projects.forms import ProjectForm

projects = Blueprint('projects', __name__)


@projects.route('/project/<int:project_id>', methods=['GET'])
def project(project_id):
	"""
	This page displays an already-existing project.

	:param project_id: The ID of the project to be read from the database and presented in a HTML format.
	:return: HTML page presenting the desired project.
	"""
	g = OAuth2Session(client_id, token=session['oauth_token'])
	project_to_display = Project.query.get_or_404(project_id)
	repository = g.get(project_to_display.github_repo)

	def retrieve_readme():
		"""
		Request the README of a valid Github repository. If successful, decode the contents of the response.

		:return: String, ready for Markdown.
		:except: If no README is found, return an error message.
		"""

		try:
			request_readme = g.get(f'https://api.github.com/repos{repository.request.path_url}/contents/README.md?ref=main').json()
			readme = base64.b64decode(request_readme['content']).decode()	# base64 -> bytes -> string
			return readme
		except KeyError:
			error_text = f"Github API: 404 Not Found."
			return error_text

	def retrieve_license():
		"""
		Request the LICENSE of a valid Github repository. If successful, request the API URL of the license.
		:return: JSON-encoded contents of the response.
		:except: If no license is found, return a 'pseudo-response'.
		"""

		try:
			request_license = g.get(f'https://api.github.com/repos{repository.request.path_url}/license').json()
			request_license_json = request_license['license']
			license_json = g.get(f"https://api.github.com/licenses/{request_license_json['key']}").json()
			return license_json
		except KeyError:
			no_license = {'html_url': 'https://choosealicense.com/no-permission/', 'name': 'no license'}
			return no_license

	project_readme = retrieve_readme()
	project_license = retrieve_license()

	return render_template(
		'project_view.html',
		title=project_to_display.title,
		project=project_to_display,
		readme=project_readme,
		license=project_license)


@projects.route('/project/new', methods=['GET', 'POST'])
@login_required
def project_form():
	"""This is the page for creating a new project"""

	form = ProjectForm()
	tags = form.dropdown_tags

	if form.validate_on_submit():
		form_data_contributors = form.contributors.data.split(', ')
		project_contributors = []

		"""If the user assigns no contributors, the current user is defined as the sole contributor."""
		if form_data_contributors[0] == '':
			project_contributors.insert(0, current_user)
		else:
			for c in range(len(form_data_contributors)):
				contributor = User.query.filter_by(username=form_data_contributors[c]).first()
				project_contributors.append(contributor)
				project_contributors.insert(0, current_user)

		new_project = Project(title=form.title.data,
							  content=form.content.data,
							  admin=current_user,
							  contributors=project_contributors,  # wants User objects, not names or IDs!
							  github_repo=form.github_repo.data,
							  tag=form.tag.data
							  )

		db.session.add(new_project)
		db.session.commit()

		flash('Your project is live!', 'success')
		return redirect(url_for('main.home'))

	return render_template('project_form.html', form=form, type='project', tags=tags)

tbcompanion/users/routes.py
from flask import Blueprint, render_template, request, url_for
from flask.helpers import flash
from flask_login import login_user, logout_user
from flask_login.utils import login_required
from werkzeug.utils import redirect

from tbcompanion import bcrypt
from tbcompanion.models import Post, User
from tbcompanion.users.forms import LoginForm

users = Blueprint('users', __name__)


@users.route('/login', methods=['GET', 'POST'])
def login():
	"""This is the page where registered users can log in."""

	form = LoginForm()

	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.remember.data)
			after_login_page = request.args.get('next')  # Allows returning users to the page they were on previously.
			flash(f'Welcome back, {user.username}!', 'success')
			return redirect(after_login_page) if after_login_page else redirect(url_for('main.home'))
		else:
			flash('Login unsuccessful. :(', 'danger')

	return render_template('login.html', title='Login', form=form)


@users.route('/logout', methods=['GET'])
def logout():
	"""Logout route."""
	logout_user()
	flash('You are logged out. See ya\'!', 'info')
	return redirect(url_for('main.home'))


@users.route('/users')
@login_required
def search_users():
	"""Displays a list of all registered users."""
	user_search = User.query.all()
	return render_template('user_search.html', 
		users=user_search,
		title='Users')


@users.route('/users/<int:user_id>')
@login_required
def user_profile(user_id):
	"""This page displays the profile of a different registered user to the current user."""

	user = User.query.get_or_404(user_id)
	posts = Post.query.filter_by(author=user)
	projects = user.contribution_id

	return render_template('user_profile.html', 
		user=user, 
		posts=posts, 
		projects=projects,
		title=user.username)

tbcompanion/templates/account.html
{% extends 'layout.html' %}

{% block feed %}
<caption><h3>{{ user.username }}'s posts</h3></caption>
<table class="striped-table hover-table container-fluid">
	<thead>
    	<tr>
			<th scope="col">id</th>
    	  	<th scope="col">Title</th>
    	  	<th scope="col">Author</th>
            <th scope="col">Related to project</th>
    	  	<th scope="col">Date posted</th>
    	  	<th scope="col">Last updated</th> 
			  <!-- TODO: Update user post list -->

    	</tr>
  	</thead>
	<tbody>
		{% for post in posts %}
		<tr>
            <th scope="col">{{ post.id }}</th>
			<td><a class="text-reset" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></td>
            <td><a class="text-reset" href="{{ url_for('users.user_profile', user_id=post.author.id) }}">{{ post.author.username }}</a></td>
            <td>None</td>
            <td>{{ post.date.strftime('%Y.%m.%d') }}</td>
			<td>Never</td>
		</tr>
		{% endfor %}
    </tbody>
</table>
<p></p>

<caption><h3>{{ user.username }}'s projects</h3></caption>
<table class="striped-table hover-table container-fluid">
	<thead>
    	<tr>
			<th scope="col">id</th>
    	  	<th scope="col">Title</th>
    	  	<th scope="col">Contributors</th>
            <th scope="col">Tags</th>
    	  	<th scope="col">Date posted</th>
    	  	<th scope="col">Last updated</th>
    	</tr>
  	</thead>
	<tbody>
		{% for project in projects %}
		<tr>
            <th scope="col">{{ project.id }}</th>
			<td><a class="text-reset" href="{{ url_for('projects.project', project_id=project.id) }}">{{ project.title }}</a></td>
			<td>
			{% for contributor in project.contributors %}
            <a class="text-reset" href="{{ url_for('users.user_profile', user_id=contributor.id) }}">{{ contributor.username }}</a>
			{% endfor %}
			</td>
            <td>None</td>
            <td>{{ project.date.strftime('%Y.%m.%d') }}</td>
			<td>Never</td>
		</tr>
		{% endfor %}
    </tbody>
</table>
{% endblock feed %}


{% block update_account %}
<hr/>
<div>
	<form method="POST" action="">
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<legend>Update account details</legend>
			<div>
				{{ form.username.label(class="form-control-label") }}
				<!-- Begin invalid form -->
				{% if form.username.errors %}
					{{ form.username(class="form-control form-control-lg is-invalid") }}
					<div class='invalid-feedback'>
						{% for error in form.username.errors %}
							<span>{{ error }}</span>
						{% endfor %}
					</div>
				<!-- End invalid form -->
				{% else %}
					{{ form.username(class="form-control form-control-lg") }}
				{% endif %}
			</div>
			<div>
				{{ form.email.label(class="form-control-label") }}
				<!-- Begin invalid form -->
				{% if form.email.errors %}
					{{ form.email(class="form-control form-control-lg is-invalid") }}
					<div class='invalid-feedback'>
						{% for error in form.email.errors %}
							<span>{{ error }}</span>
						{% endfor %}
					</div>
				<!-- End invalid form -->
				{% else %}
					{{ form.email(class="form-control form-control-lg") }}
				{% endif %}
			</div>
		</fieldset>
		<p></p>
		<div>
			{{ form.submit(class="btn btn-outline-info") }}
		</div>
		<!-- TODO: Button padding-bottom -->
	</form>
</div>
{% endblock update_account %}

tbcompanion/templates/admin.html
{% extends 'layout.html' %}

<!-- TODO: Restrict access to user.is_admin == True -->
<!-- TODO: Implement -->

<form method = 'POST' action=''>
	<fieldset class='form-group'>
		<legend>Empty form</legend>
			<div class='container'>

			</div>
	</fieldset>
</form>

tbcompanion/templates/home.html
{% extends 'layout.html' %}

<!-- TODO: Reformat 'feed' block -->
<!-- TODO: Search -->

{% block content %}

<form method = 'POST' action =''>
	{{ form.hidden_tag() }}
	<fieldset class = 'form-group'>
		<div class = 'container'>
			<div>{{ form.string.label(class="form-control-label") }}
			<!-- Begin invalid form -->
			{% if form.string.errors %}
				{{ form.string(class="form-control is-invalid") }}
				<div class='invalid-feedback'>
					{% for error in form.string.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
		<!-- End invalid form -->
			{% else %}
				{{ form.string(class="form-control")}}
			{% endif %}
			</div>
		</div>
	</fieldset>
</form>

<a href="{{ url_for('.github_authorization') }}">To avoid API errors, authorize this app by following this link.</a>

{% endblock content %}

{% block feed %}
<div class="row">
	<div class="col">
		<h1>Posts</h1>
		{% for post in posts %}
		<div class="container bg-light pt-2 pb-2 margin">
			<a class="text-reset" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a>
			
			
			<p>{{ post.date.strftime('%A, the %dth of %B %Y') }}</p>
			<p>{{ post.content|markdown }}</p>
			<p>By <a href="{{ url_for('users.user_profile', user_id=post.author.id) }}">{{ post.author.username }}</a></p>
		</div>

		<p></p>
		{% endfor %}
	</div>
	<div class='col'>
		<h1>Projects</h1>
	{% for project in projects %}
		<div class="container bg-light pt-2 pb-2 margin">
			<a href="{{ url_for('projects.project', project_id=project.id) }}">{{ project.title }}</a> [{{ project.tag }}]</h3>

			<p>{{ project.content|markdown }}</p>
			Contributors: 
			{% for contributor in project.contributors %}
			<a href="{{ url_for('users.user_profile', user_id=contributor.id) }}">{{ contributor.username }}</a>
			{% endfor %}
			<p><a href="{{ project.github_repo }}">{{ project.title }} on GitHub</a></p></small>
		</div>
		<p></p>
	{% endfor %}
	</div>
</div>
{% endblock feed %}

tbcompanion/templates/layout.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		{{ pagedown.include_pagedown() }}

		<!-- Custom CSS -->
		<link
		rel="stylesheet"
		type="text/css"
		href="{{ url_for('static', filename= 'main.css') }}"
		/>
	
		<!-- Bootstrap CSS -->
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl"
			crossorigin="anonymous"
		/>


		<!-- Automatic title -->
		{% if title %}
			<title>TBCOMP::{{ title }}</title>
		{% else %}
			<title>TBCOMP</title>
		{% endif %}
	</head>
	<!-- shoulderskneesandtoes,kneesandtoes,headshoulderskneesandtoes,kneesandtoes,andeyesandearsandmothandnose,heaaaadshoulderskneesandtoes,kneesandtoes!!!!!! -->


<!-- Navbar -->

		
	<body>

		<div class="sidebar">
			<ul class="navbar-nav">
				<a class="logo" href="{{url_for('main.home')}}">TBCOMP::</a>
				{% if current_user.is_authenticated %}
				<li class="navbar-item"><a class="nav-link" href="{{url_for('users.search_users')}}">registered users</a></li>
				<li class="navbar-item"><a class="nav-link" href="{{url_for('posts.post_form')}}">make a post</a></li>
				<li class="navbar-item"><a class="nav-link" href="{{url_for('projects.project_form')}}">release a project</a></li>

				{% if current_user.is_admin %}
				<li class="navbar-item"><a class="nav-link" href="{{url_for('admin.admin_panel')}}">admin</a></li>
				{% endif %}

				<li class="navbar-item"><a class="nav-link" href="{{url_for('accounts.account_page')}}">account</a></li>
				<li class="navbar-item"><a  id='logout' class="nav-link" href="{{url_for('users.logout')}}">logout</a></li>
				{% else %}
				<li class="navbar-item"><a class="nav-link" href="{{url_for('main.about')}}">about</a></li>
				<li class="navbar-item"><a class="nav-link" href="{{url_for('users.login')}}">log in</a></li>
				<li class="navbar-item"><a class="nav-link" href="{{url_for('accounts.register')}}">register</a></li>
				{% endif %}
			</ul>
		</div>
			<!-- Begin alert bar -->
			{% with messages = get_flashed_messages(with_categories=True) %}
				{% if messages %}
					{% for category, message in messages %}
						<div class="alert alert-{{category}}">{{ message }}</div>
					{% endfor %}
				{% endif %}
			{% endwith %}
			<!-- End alert bar -->

			{% block content %}
			{% endblock content %}

			{% block feed %}
			{% endblock feed %}

			{% block update_account %}
			{% endblock update_account %}

		</div>

		<!-- Bootstrap Bundle with Popper booper boopidiboop-->
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js",
				integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN",
				crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js",
				integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q",
				crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js",
				integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl",
				crossorigin="anonymous"></script>
	</body>
</html>

tbcompanion/templates/post_view.html
{% extends 'layout.html' %}

{% block content %}

	<h1>{{ post.title }}</h1>
	<p>By {{ post.author.username }} on {{ post.date.strftime('%A, the %dth of %B %Y') }}</p>
	<p>{{ post.content|markdown }}</p>
	{% if post.author == current_user %}

	<!-- TODO: Restyle button -->
		<a type="button" class="btn btn-secondary" href="{{url_for('posts.update_post', post_id=post.id)}}">Update</a>
		<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">Delete</button>

	{% endif %}
<!-- Button trigger modal -->

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
		  Are you sure you want to delete this post?<p><b>This cannot be undone.</b></p>
      </div>
      <div class="modal-footer">
		  <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
			  <input class="btn btn-danger" type="submit" value="Yes, I'm sure!">
		  </form>
		  <button type="button" class="btn btn-primary" data-dismiss="modal">No, take me back!</button>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

tbcompanion/templates/project_view.html
{% extends 'layout.html' %}

{% block content %}

	<h1>{{ project.title }} | {{ project.id }}</h1>
	<p>Contributors:
	{% for contributor in project.contributors %}
		{{ contributor }}
	{% endfor %}</p>
	<p>Published on {{ project.date.strftime('%A, the %dth of %B %Y') }}
		under <a href="{{ license['html_url'] }}">{{ license['name'] }}</a></p>
	{{ project.content|markdown }}
	<h3>README</h3>
	{{ readme|markdown }}


	

	<!-- TODO: Include tags -->
	<!-- TODO: Implement rich text -->
	<!-- TODO: Update button -->
	<!-- TODO: Delete button -->
	<!-- TODO: Template formatting -->
	<!-- TODO: 'Last updated on' -->
{% endblock content %}

tbcompanion/templates/user_profile.html
{% extends 'account.html' %}


{% block update_account %}
{% endblock update_account %}